export const DASHBOARD = '/'
export const LOGIN = '/login'
export const SIGN_UP = '/signup'
export const PROFILE = '/profile/:username'
export const NOT_FOUND = '/not_found'
export const FORGOT_PASSWORD = '/forgot_password'